version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql

  achat-backend:
    image: intissartm/docker-project-backend-achat-backend:v2
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - 8087:8087
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    depends_on:
      - mysqldb

  front:
      image: intissartm/ang-app:v1
    deploy:
      replicas: 2
    ports:
      - "86:86"

volumes:
  db:
